family: "$ECS_WEB_TASK"
networkMode: awsvpc
cpu: "$ECS_WEB_TASK_CPU_UNITS"
memory: "$ECS_WEB_TASK_MEMORY_UNITS"
executionRoleArn: "$ROLE_ARN"
taskRoleArn: "$ROLE_ARN"
requiresCompatibilities:
  - FARGATE
containerDefinitions:
  - name: logs
    image: public.ecr.aws/aws-observability/aws-for-fluent-bit:stable
    firelensConfiguration:
      type: fluentbit
    memoryReservation: 50
    logConfiguration:
      logDriver: awslogs
      options:
        awslogs-group: "/analysistools/$TIER/$APP/web"
        awslogs-region: "$AWS_REGION"
        awslogs-stream-prefix: logs

  - name: backend
    image: "$BACKEND_IMAGE_LATEST"
    environment:
      - name: FLASK_ENV
        value: "production"
      - name: PYTHONUNBUFFERED
        value: "1"
      - name: TZ
        value: "${TZ}"
    portMappings:
      - protocol: tcp
        containerPort: $BACKEND_CONTAINER_PORT
    logConfiguration:
      logDriver: awsfirelens
      options:
        Name: datadog
        tls: "on"
        tls.verify: "off"
        dd_service: "$TIER-$APP-backend"
        dd_source: "flask"
        dd_tags: "project:$APP tier:$TIER"
        provider: ecs
      secretOptions:
        - name: Host
          valueFrom: /analysistools/$TIER/datadog/log_endpoint_host
        - name: apikey
          valueFrom: /analysistools/$TIER/datadog/api_key
tags:
  - key: "ApplicationName"
    value: "$APP"
  - key: "Project"
    value: "dceg-analysistools"
  - key: "ResourceName"
    value: "$TIER-$APP-web-task"
  - key: "EnvironmentTier"
    value: "$ENVIRONMENT_TIER"
  - key: ResourceFunction
    value: compute
