services:
  apc:
    build:
      context: .
      dockerfile: docker/backend.dockerfile
    container_name: apc-tool
    ports:
      - "10000:80"
    volumes:
      - ./tmp:/app/tmp
    restart: unless-stopped
